name: Build and deploy
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step.outputs.test }}
      upload_url: ${{ steps.print_create_release.outputs.test }}
    steps:
      - id: step
        run: echo "test=AAAAAAAAAA!!!!" >> "$GITHUB_OUTPUT"
      - id: print_create_release
        run: echo "test=BBBBBBBBBBBBB!!!!" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.create_release.outputs.output1}}
          OUTPUT2: ${{needs.print_create_release.outputs.upload_url}}
        run: echo "$OUTPUT1 $OUTPUT2"
