name: Build and deploy
on: workflow_dispatch
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    outputs:
      uploadurl1: ${{ steps.print_create_release.outputs.uploadurl }}
      #output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #tag_name: ${{ github.ref }}
          tag_name: ${{ github.run_number }}
          #release_name: Release ${{ github.ref }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - id: print_create_release
        run: echo "uploadurl=http" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - env:
          OUTPUT1: ${{needs.create_release.outputs.uploadurl1}}
          #OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1"
