name: Build and deploy
on: workflow_dispatch
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    outputs:
      upload_url: ${{ steps.print_create_release.outputs.upload_url }}
      #output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #tag_name: ${{ github.ref }}
          tag_name: ${{ github.run_number }}
          #release_name: Release ${{ github.ref }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - id: print_create_release
        run: echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - env:
          OUTPUT1: ${{needs.print_create_release.outputs.upload_url}}
          #OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1"
