name: upload-to-release-win

on: 
  release:
    types:
      - created

jobs:
  job:
    name: Upload Release Asset Windows
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Upload to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          upload_url: ${{ github.event.release.upload_url }} #${{ steps.create_release.outputs.upload_url }} 
          asset_path: ${{ github.workspace }}/cmakepresets/builds/ninja-multi-vcpkg/buildeploy-0.0.${{ github.run_number }}-win64.zip
          asset_name: buildeploy-0.0.${{ github.run_number }}-win64.zip
         # D:/a/buildeploy/buildeploy/cmakepresets/builds/ninja-multi-vcpkg/buildeploy-0.0.41-win64.zip
          asset_content_type: application/zip

